version: "1"
rules:
  - base: master
    upstream: dracula/tmux:master
    mergeMethod: merge
    conflictReviewers:
      - xiao0yy
label: ":arrow_heading_down: pull"
conflictLabel: "merge-conflict"

